# Generated by Django 2.2.7 on 2019-11-09 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('real_amount', models.FloatField()),
                ('channel', models.CharField(choices=[('WEB', 'Web'), ('WAP', 'App')], default='WEB', max_length=3)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_txn_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Failure'), ('P', 'Pending'), ('U', 'Unknown'), ('E', 'Fraud')], default='U', max_length=20)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('resp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('resp_message', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.CharField(blank=True, max_length=15, null=True)),
                ('bank', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=15, null=True)),
                ('initiated', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
